import os
from django.conf import settings

# NOVA CONFIGS
NOVA_FLOATING_IP_CREATION = True
NOVA_FLOATING_IP_POOL = 'public'

NOVA_IMAGE_NAME = "ubuntu"

NOVA_QUOTA_INSTANCES = -1
NOVA_QUOTA_CORES = -1
NOVA_QUOTA_RAM = -1
NOVA_QUOTA_FIXED_IPS = -1
NOVA_QUOTA_FLOATING_IPS = -1

NOVA_VM_FLAVOR = "traffic"
NOVA_VM_FLAVOR_RAM = 2048   # In Mega Bytes
NOVA_VM_FLAVOR_VCPUS = 1
NOVA_VM_FLAVOR_DISK = 10    # In Giga Bytes


# GLANCE CONFIGS
GLANCE_ENDPOINT = "http://172.168.2.40:9292"

GLANCE_IMAGE_NAME = NOVA_IMAGE_NAME
GLANCE_IMAGE_PATH = os.path.join(settings.MEDIA_ROOT, os.path.join("osimages", "ubuntu.img"))
GLANCE_IMAGE_DISK_FORMAT = "qcow2"
GLANCE_IMAGE_CONTAINER_FORMAT = "bare"

