# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subnet',
            name='allocation_pool_end_selected',
        ),
        migrations.RemoveField(
            model_name='subnet',
            name='allocation_pool_start_selected',
        ),
    ]
