# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-04 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subnet',
            old_name='allocation_range_end',
            new_name='allocation_pool_end',
        ),
        migrations.RenameField(
            model_name='subnet',
            old_name='allocation_range_start',
            new_name='allocation_pool_end_selected',
        ),
        migrations.RenameField(
            model_name='subnet',
            old_name='selected_allocation_range_end',
            new_name='allocation_pool_start',
        ),
        migrations.RenameField(
            model_name='subnet',
            old_name='selected_allocation_range_start',
            new_name='allocation_pool_start_selected',
        ),
    ]
