# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 10:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 18, 10, 57, 43, 702918, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='network',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 18, 10, 57, 43, 702965, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='router',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 18, 10, 57, 43, 704316, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='router',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 18, 10, 57, 43, 704362, tzinfo=utc)),
        ),
    ]
