# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traffic',
            name='tenants',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
