# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traffic',
            name='tenants',
            field=models.ManyToManyField(related_name='tenants', to='cloud.Tenant'),
        ),
    ]
