# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_auto_20160405_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traffic',
            name='selected_networks',
            field=models.ManyToManyField(blank=True, related_name='selected_networks', through='cloud.TrafficNetworksMap', to='cloud.Network'),
        ),
    ]
