# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 11:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_auto_20160318_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 18, 11, 52, 59, 534942, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='network',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 18, 11, 52, 59, 534987, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='router',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 18, 11, 52, 59, 536327, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='router',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 18, 11, 52, 59, 536372, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 18, 11, 52, 59, 533215, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 18, 11, 52, 59, 533260, tzinfo=utc)),
        ),
    ]
