# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0003_auto_20160315_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traffic',
            name='tenants',
            field=models.ManyToManyField(blank=True, null=True, to='cloud.Tenant'),
        ),
    ]
