# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0003_auto_20160411_0703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_id', models.CharField(max_length=100)),
                ('endpoint_name', models.CharField(max_length=100)),
                ('endpoint_ip_address', models.CharField(max_length=30)),
                ('endpoint_status', models.CharField(max_length=30)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.Network')),
                ('traffic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.Traffic')),
            ],
            options={
                'db_table': 'cloud_traffic_endpoints',
            },
        ),
    ]
