# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 06:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0003_auto_20160318_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='is_dirty',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='network',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 21, 6, 21, 29, 228959, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='network',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 21, 6, 21, 29, 229004, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='router',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 21, 6, 21, 29, 230319, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='router',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 21, 6, 21, 29, 230377, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 21, 6, 21, 29, 227286, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 21, 6, 21, 29, 227333, tzinfo=utc)),
        ),
    ]
