# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0003_auto_20160225_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloudtraffic',
            name='step',
        ),
        migrations.AddField(
            model_name='cloudtraffic',
            name='external_host',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
