# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0004_endpoints'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Endpoints',
            new_name='Endpoint',
        ),
    ]
