# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0005_auto_20160321_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='is_dirty',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='router',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
