# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0006_auto_20160413_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='is_dirty',
            field=models.BooleanField(default=False),
        ),
    ]
