# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0006_auto_20160321_0634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subnet_id', models.CharField(max_length=255)),
                ('network_name', models.CharField(max_length=255)),
                ('cidr', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'cloud_tenant_network_subnets',
            },
        ),
        migrations.RemoveField(
            model_name='network',
            name='network_cidr',
        ),
        migrations.RemoveField(
            model_name='network',
            name='subnet',
        ),
        migrations.AddField(
            model_name='subnet',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subnets', to='cloud.Network'),
        ),
    ]
