# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0007_auto_20160330_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='subnet',
            name='is_dirty',
            field=models.BooleanField(default=False),
        ),
    ]
