# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0007_endpoint_is_dirty'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficnetworksmap',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trafficnetworksmap',
            name='ip_range_end',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='trafficnetworksmap',
            name='ip_range_start',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterModelTable(
            name='trafficnetworksmap',
            table='cloud_traffic_networks_map',
        ),
    ]
