# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0008_subnet_is_dirty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subnet',
            old_name='network_name',
            new_name='subnet_name',
        ),
    ]
