# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0009_auto_20160330_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='traffic',
            name='test_environment',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
