# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0010_traffic_test_environment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traffic',
            name='test_environment',
            field=models.CharField(choices=[('dev', 'Development/Test'), ('prod', 'Production')], default='all', max_length=20),
        ),
    ]
