# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-01 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0012_auto_20160331_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traffic',
            name='tenants',
            field=models.ManyToManyField(blank=True, to='cloud.Tenant'),
        ),
    ]
