# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-01 07:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0013_auto_20160401_0643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traffic',
            old_name='tenant_type',
            new_name='test_type',
        ),
    ]
