# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-01 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0014_auto_20160401_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subnet',
            name='allocation_range_end',
            field=models.GenericIPAddressField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subnet',
            name='allocation_range_start',
            field=models.GenericIPAddressField(default=''),
            preserve_default=False,
        ),
    ]
