# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-01 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0015_auto_20160401_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='subnet',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subnet',
            name='selected_allocation_range_end',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subnet',
            name='selected_allocation_range_start',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='allocation_range_end',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='allocation_range_start',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
